# Generated by Django 4.2.7 on 2023-11-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='modified_date',
        ),
    ]
